# Generated by Django 3.1.2 on 2022-08-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=99)),
                ('last_name', models.CharField(max_length=99)),
                ('username', models.CharField(max_length=99)),
                ('email', models.CharField(max_length=99)),
                ('phone', models.CharField(max_length=99)),
                ('profession', models.CharField(max_length=99)),
                ('bio', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('linkedin', models.CharField(max_length=99)),
                ('facebook', models.CharField(max_length=99)),
                ('github', models.CharField(max_length=99)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
