# Generated by Django 3.1.2 on 2022-08-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='userprofile',
        ),
    ]
