# Generated by Django 3.1.2 on 2022-08-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220830_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='facebook',
            new_name='account_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profession',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interest',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_role',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
