# Generated by Django 3.1.2 on 2022-08-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220831_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=99, null=True)),
                ('username', models.CharField(blank=True, max_length=99, null=True)),
                ('email', models.CharField(blank=True, max_length=99, null=True)),
                ('job_category', models.CharField(blank=True, max_length=99, null=True)),
                ('job_amount', models.CharField(blank=True, max_length=99, null=True)),
                ('job_detail', models.CharField(blank=True, max_length=300, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
