# Generated by Django 3.1.2 on 2022-09-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220831_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='gig_database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=99, null=True)),
                ('username', models.CharField(blank=True, max_length=99, null=True)),
                ('email', models.CharField(blank=True, max_length=99, null=True)),
                ('phone', models.CharField(blank=True, max_length=99, null=True)),
                ('bio', models.CharField(blank=True, max_length=300, null=True)),
                ('job_role', models.CharField(blank=True, max_length=300, null=True)),
                ('interest', models.CharField(blank=True, max_length=300, null=True)),
                ('money', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
