# Generated by Django 3.1.2 on 2022-09-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_gig_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=99, null=True)),
                ('username', models.CharField(blank=True, max_length=99, null=True)),
                ('email', models.CharField(blank=True, max_length=99, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
