# Generated by Django 3.1.2 on 2022-09-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_job_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_request',
            new_name='job_request_database',
        ),
    ]
