# Generated by Django 3.1.2 on 2022-09-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220904_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_request_database',
            name='request_id',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
