# Generated by Django 3.1.2 on 2022-09-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_job_request_database_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_request_database',
            name='request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
